config/routes.rb
Gitlaw::Application.routes.draw do
  resources :modifications do
    member do
      get :compare
    end
  end
  
  resources :texts
  resources :users

  devise_for :users, path: 'auth', controllers: {registrations: "registrations"}

  root :to =>  "home#index"
  
  match ':user_id/:text_id/:id' => 'modifications#show', as: :full_modification
  match ':user_id/:text_id/:id/compare' => 'modifications#compare', as: :full_compare_modification
  match ':user_id/:id' => 'texts#show', as: :full_text

end

app/models/modification.rb
class Modification < ActiveRecord::Base
  include ActiveSupport::Inflector

  attr_accessible :description, :text, :title, :original_id, :slug
  
  belongs_to :original, class_name: "Modification"
  belongs_to :repository, class_name: "Text"
  
  delegate :user, to: :repository

  before_save :commit_text
  
  before_validation :initialize_slug
  extend FriendlyId
  friendly_id :slug, use: []
  def initialize_slug
    self.slug = transliterate(title).downcase.strip.gsub(/\s+/, '-') if slug.blank? and title.present?
  end

  def create_repository(user)
    return if repository
    
    raise "Original required" unless original
    raise "User required" unless user
    self.repository = user.texts.where(slug: original.repository.slug).first_or_initialize(title: original.repository.title)
    self.repository.user = user
    self.repository.save!
  end

  def commit_text
    return if text.blank?
    
    repo = Rugged::Repository.new(repository.repository_path.to_s)
    
    oid = repo.write(self.text, :blob)
    index = Rugged::Index.new
    index.add(:path => "#{repository.title}.txt", :oid => oid, :mode => 0100644)

    options = {}
    options[:tree] = index.write_tree(repo)

    options[:author] = { :email => "testuser@github.com", :name => 'Test Author', :time => Time.now }
    options[:committer] = { :email => "testuser@github.com", :name => 'Test Author', :time => Time.now }
    options[:message] ||= "Making a commit via Rugged!"

    if head
      options[:parents] = [head]
    elsif original
      options[:parents] = [original.head]
      
      unless repo.exists?(original.head)
        original_repository = Rugged::Repository.new(original.repository.repository_path.to_s)
        walker = Rugged::Walker.new(original_repository)
        walker.sorting(Rugged::SORT_TOPO | Rugged::SORT_REVERSE)
        walker.push(original.head)
        walker.each do |commit|
          break if repo.exists?(commit.oid)
          new_commit = commit.to_hash
          
          builder = Rugged::Tree::Builder.new
          commit.tree.each do |entry|
            unless repo.exists?(entry[:oid])
              obj = original_repository.read(entry[:oid])
              repo.write(obj.data, obj.type)
            end
            builder << entry
          end
          new_commit[:tree] = builder.write(repo)
          new_commit[:parents] = new_commit[:parents].map(&:oid)
          
          Rugged::Commit.create(repo, new_commit)
        end
      end
    else
      options[:parents] = []
    end

    new_sha1 = Rugged::Commit.create(repo, options)
    
    branch = slug
    ref_path = "refs/heads/#{branch}"
    ref = Rugged::Reference.lookup(repo, ref_path)
    if ref
      ref.set_target(new_sha1)
    else
      ref = Rugged::Reference.create(repo, ref_path, new_sha1)
    end
    
    self.head = new_sha1
  end
  
  def master?
    slug == "master"
  end
end

app/controllers/modifications_controller.rb
class ModificationsController < ApplicationController
  before_filter :require_user, only: [:new]
  load_and_authorize_resource
  
  include ApplicationHelper

  # GET /modifications
  # GET /modifications.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @modifications }
    end
  end

  # GET /modifications/1
  # GET /modifications/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @modification }
    end
  end

  # GET /modifications/new
  # GET /modifications/new.json
  def new
    if params[:original_id].present?
      @modification.original = Modification.accessible_by(current_ability).find(params[:original_id])
      @modification.text = params[:text] || @modification.original.try(:text)
    end
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @modification }
    end
  end

  # GET /modifications/1/edit
  def edit
  end

  # POST /modifications
  # POST /modifications.json
  def create
    respond_to do |format|
      if params[:original_id].present?
        @modification.original = Modification.accessible_by(current_ability).find(params[:original_id])
      end
      @modification.create_repository(current_user)
      if @modification.save
        format.html { redirect_to expanded_modification_path(@modification), flash: {success: t("modifications.created")} }
        format.json { render json: @modification, status: :created, location: @modification }
      else
        format.html { render action: "new" }
        format.json { render json: @modification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /modifications/1
  # PATCH/PUT /modifications/1.json
  def update
    respond_to do |format|
      if @modification.update_attributes(params[:modification])
        format.html { redirect_to @modification, flash: {success: t("modifications.updated")} }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @modification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /modifications/1
  # DELETE /modifications/1.json
  def destroy
    @modification.destroy

    respond_to do |format|
      format.html { redirect_to modifications_url }
      format.json { head :no_content }
    end
  end
end

app/views/modifications/_action_bar.html.haml
- except ||= []
.affix-action-bar-parent{class: "span#{span}"}
  .affix-action-bar
    = link_to t('.compare_original'), compare_modification_path(@modification), :class => 'btn btn-block' if !except.include?(:compare) and @modification.original and can? :read, @modification.original
    = link_to t('.show'), expanded_modification_path(@modification), :class => 'btn btn-block' if !except.include?(:show) and can? :read, @modification
    = link_to t('.edit'), edit_modification_path(@modification), :class => 'btn btn-block' if can? :update, @modification
    = link_to t('.new_modification'), new_modification_path(original_id: @modification.id), :class => 'btn btn-block'
    = link_to t('.show_original'), expanded_modification_path(@modification.original), :class => 'btn btn-block' if @modification.original and can? :read, @modification.original
    = link_to t('.destroy'), modification_path(@modification), :method => "delete", :confirm => t('.confirm'), :class => 'btn btn-danger btn-block' if can? :destroy, @modification
    - modifications = ::Text.where(slug: @modification.repository.slug).includes(:modifications).map(&:modifications).flatten(1) - [@modification]
    - if modifications.any?
      %h3= t(".modifications")
      %ul
        - modifications.each do |modification|
          %li
            = link_to_modification(modification)
            = "(#{link_to_user(modification.repository.user)})".html_safe

app/views/modifications/_form.html.haml
= bootstrap_form_for @modification, :html => { :class => 'form-horizontal' } do |f|
  = f.hidden_field :original_id
  = f.text_field :title, class: 'input-block-level'
  = f.text_area :description, class: 'input-block-level', rows: 3
  = f.text_area :text, class: 'input-block-level', rows: 10
  
  .form-actions
    = f.submit t('.submit'), :class => 'btn btn-primary'
    = link_to t('.cancel'), modifications_path, :class => 'btn'

app/views/modifications/compare.html.haml
- content_for(:title, t(".title", name: @modification.title))
- add_crumb @modification.user.display_name, user_path(@modification.user)
- add_crumb @modification.repository.title, expanded_text_path(@modification.repository)
- add_crumb @modification.title, expanded_modification_path(@modification)
- add_crumb t(".breadcrumb_title")

.row
  = render "modifications/action_bar", span: 2, except: [:compare]
      
  .span10
    .row
      .span5
        %h2= t(".original_text")
      .span5
        %h2= t(".modified_text")
    .text-diff
      - diff_lines(@modification.original.text, @modification.text).each do |kind, lines|
        .diff-group{class: kind}
          .row.line-count
            .span10= t(".line_count", count: lines.count)
          .lines
            - lines.each do |old, new|
              .row
                .span5
                  %p!= old
                .span5
                  %p!= new

app/views/modifications/edit.html.haml
- content_for :title, t('.title', name: @modification.title)
- add_crumb @modification.user.display_name, user_path(@modification.user)
- add_crumb @modification.repository.title, expanded_text_path(@modification.repository)
- add_crumb @modification.title, expanded_modification_path(@modification)
- add_crumb t(".breadcrumb_title")

.row
  .span12
    = render :partial => "form"

app/views/modifications/index.html.haml
- content_for :title, t('.title')

.row
  .span12
    - if @modifications.blank?
      %p.alert.alert-notice= t(".empty")
    - else
      %table.table.table-striped
        %thead
          %tr
            %th= Modification.human_attribute_name(:user_id)
            %th= Modification.human_attribute_name(:original_id)
            %th= Modification.human_attribute_name(:title)
            %th= Modification.human_attribute_name(:motivations)
            %th= Modification.human_attribute_name(:text)
            %th= t('.actions')
        %tbody
          - @modifications.each do |modification|
            %tr
              %td= modification.user_id
              %td= modification.original_id
              %td= modification.title
              %td= modification.motivations
              %td= modification.text
              %td
                = link_to t('.show'), modification_path(modification), :class => 'btn btn-mini'
                = link_to t('.edit'), edit_modification_path(modification), :class => 'btn btn-mini' if can? :update, modification
                = link_to t('.destroy'), modification_path(modification), :method => :delete, :confirm => t('.confirm'), :class => 'btn btn-mini btn-danger' if can? :destroy, modification

    = link_to t('.new'), new_modification_path, :class => 'btn btn-primary' if can? :create, ::Modification

app/views/modifications/new.html.haml
- content_for :title, t('.title')
- add_crumb content_for(:title)

.row
  .span12
    = render :partial => "form"

app/views/modifications/show.html.haml
- content_for(:title, t(".title", name: @modification.title))
- add_crumb @modification.user.display_name, user_path(@modification.user)
- add_crumb @modification.repository.title, expanded_text_path(@modification.repository)
- add_crumb @modification.title

.row
  = render "modifications/action_bar", span: 3, except: [:show]
      
  .span9
    %h1.text-title= @modification.repository.title
    %h2.modification-title= @modification.title
    %p.modification-description= @modification.description
    .text-text
      - @modification.text.split(/\n/).each do |line|
        - case line
          - when /^Préambule/
            %h3.preamble= line
          - when /^Titre /
            %h2.title= line
          - when /^Article /
            %h3.article= line
          - when /^- /
            %p.list-item= line
          - else
            %p.paragraph= line