config/routes.rb
Gitlaw::Application.routes.draw do
  resources :modifications do
    member do
      get :compare
    end
  end
  
  resources :texts
  resources :users

  devise_for :users, path: 'auth', controllers: {registrations: "registrations"}

  root :to =>  "home#index"
  
  match ':user_id/:text_id/:id' => 'modifications#show', as: :full_modification
  match ':user_id/:text_id/:id/compare' => 'modifications#compare', as: :full_compare_modification
  match ':user_id/:id' => 'texts#show', as: :full_text

end

app/models/text.rb
class Text < ActiveRecord::Base
  include ActiveSupport::Inflector

  attr_accessible :text, :title, :base_id, :slug, :modifications_attributes
  
  belongs_to :base, class_name: "Text"
  belongs_to :user, inverse_of: :texts
  
  has_many :modifications, inverse_of: :repository, foreign_key: :repository_id
  accepts_nested_attributes_for :modifications
  
  validates_presence_of :user
  validates_uniqueness_of :slug, scope: :user_id

  after_validation :clean_text
  before_save :commit_text
  
  def clean_text
    self.text = self.text.gsub("\r\n", "\n") if self.text
  end

  before_validation :initialize_slug
  extend FriendlyId
  friendly_id :slug, use: []
  def initialize_slug
    self.slug = transliterate(title).downcase.strip.gsub(/\s+/, '-') if slug.blank? and title.present?
  end
  
  def repository_path
    raise "User is required" unless user
    raise "User.to_param is required" unless user.to_param.present?
    raise "to_param is required" unless to_param.present?
    Rails.root.join("db", "repositories", Rails.env, user.to_param, to_param + ".git")
  end
  
  def create_repository
    if base
      # Move to Rugged when https://github.com/libgit2/rugged/pull/107 is merged
      system "git", "clone", base.repository_path.to_s, repository_path.to_s
    else
      Rugged::Repository.init_at(repository_path.to_s, true)
    end
  end
  
  def commit_text
    create_repository unless repository_path.exist?
    
    return if text.blank?
    
    repo = Rugged::Repository.new(repository_path.to_s)
    
    oid = repo.write(self.text, :blob)
    index = Rugged::Index.new
    index.add(:path => "#{title}.txt", :oid => oid, :mode => 0100644)

    options = {}
    options[:tree] = index.write_tree(repo)

    options[:author] = { :email => "testuser@github.com", :name => 'Test Author', :time => Time.now }
    options[:committer] = { :email => "testuser@github.com", :name => 'Test Author', :time => Time.now }
    options[:message] ||= "Making a commit via Rugged!"
    
    ref = Rugged::Reference.lookup(repo, "refs/heads/master")
    if ref
      options[:parents] = [ref.target]
    else
      options[:parents] = []
    end

    new_sha1 = Rugged::Commit.create(repo, options)
    
    if ref
      ref.set_target(new_sha1)
    else
      ref = Rugged::Reference.create(repo, "refs/heads/master", new_sha1)
    end
    
    self.head = new_sha1
    
  end
  
  def master
    modifications.detect(&:master?)
  end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  before_filter :require_user, only: [:new]
  load_and_authorize_resource

  include ApplicationHelper
  
  # GET /texts
  # GET /texts.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @texts }
    end
  end

  # GET /texts/1
  # GET /texts/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @text }
    end
  end

  # GET /texts/new
  # GET /texts/new.json
  def new
    if params[:base_id]
      @base = Text.accessible_by(current_ability).find(params[:base_id])
      raise "Base not found" unless @base
      @text.assign_attributes @base.attributes.select { |name, value| Text.accessible_attributes.include?(name) }
      @text.base_id = @base.id
    end
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @text }
    end
  end

  # GET /texts/1/edit
  def edit
  end

  # POST /texts
  # POST /texts.json
  def create
    respond_to do |format|
      if @text.save
        format.html { redirect_to expanded_modification_path(@text.modifications.first), flash: {success: t("texts.created")} }
        format.json { render json: @text, status: :created, location: @text }
      else
        format.html { render action: "new" }
        format.json { render json: @text.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /texts/1
  # PATCH/PUT /texts/1.json
  def update
    respond_to do |format|
      if @text.update_attributes(params[:text])
        format.html { redirect_to @text, flash: {success: t("texts.updated")} }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @text.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /texts/1
  # DELETE /texts/1.json
  def destroy
    @text.destroy

    respond_to do |format|
      format.html { redirect_to texts_url }
      format.json { head :no_content }
    end
  end
end

app/views/texts/_form.html.haml
= bootstrap_form_for @text, :html => { :class => 'form-horizontal' } do |f|
  = f.text_field :title, class: 'input-block-level'
  = f.text_area :text, class: 'input-block-level', rows: 10
  
  .form-actions
    = f.submit t('.submit'), :class => 'btn btn-primary'
    = link_to t('.cancel'), texts_path, :class => 'btn'

app/views/texts/edit.html.haml
- content_for :title, t('.title', name: @text.id)
- add_crumb content_for(:title)

.row
  .span12
    = render :partial => "form"

app/views/texts/index.html.haml
- content_for :title, t('.title')

.row
  .span12
    - if @texts.blank?
      %p.alert.alert-notice= t(".empty")
    - else
      %table.table.table-striped
        %thead
          %tr
            %th= ::Text.human_attribute_name(:user)
            %th= ::Text.human_attribute_name(:title)
            %th= t('.actions')
        %tbody
          - @texts.each do |text|
            %tr
              %td= link_to_user text.user
              %td= link_to_text text, without_user: true
              %td
                = link_to t('.show'), text_path(text), :class => 'btn btn-mini'
                = link_to t('.edit'), edit_text_path(text), :class => 'btn btn-mini' if can? :update, text
                = link_to t('.destroy'), text_path(text), :method => :delete, :confirm => t('.confirm'), :class => 'btn btn-mini btn-danger' if can? :destroy, text

    = link_to t('.new'), new_text_path, :class => 'btn btn-primary' if can? :create, ::Text

app/views/texts/new.html.haml
- if @base
  - content_for(:title, t(".title_with_base", base_name: @base.title))
- else
  - content_for(:title, t(".title"))
- add_crumb current_user.display_name, current_user
- add_crumb content_for(:title)

.row
  .span12
    = bootstrap_form_for @text, :html => { :class => 'form-horizontal' } do |f|
      = f.text_field :title, class: 'input-block-level'
      = f.text_field :slug, class: 'input-block-level', placeholder: t(".slug_placeholder", default: "")
      = f.fields_for :modifications, Modification.new(slug: 'master', title: t(".master_modification")) do |fields|
        = fields.hidden_field :title
        = fields.hidden_field :slug
        = fields.text_area :description, class: 'input-block-level', rows: 3
        = fields.text_area :text, class: 'input-block-level', rows: 10, label: t(".modification_text")
      
      .form-actions
        = f.submit t('.submit'), :class => 'btn btn-primary'
        = link_to t('.cancel'), texts_path, :class => 'btn'

app/views/texts/show.html.haml
- content_for(:title, t(".title", name: @text.title))
- add_crumb(@text.user.display_name, @text.user) if @text.user
- add_crumb content_for(:title)

.row
  .span3.affix-action-bar-parent
    .affix-action-bar
      - if @text.master
        = link_to t('.new_modification'), new_modification_path(original_id: @text.master.id), :class => 'btn btn-primary btn-block'
      = link_to t('.edit'), edit_text_path(@text), :class => 'btn btn-block' if can? :update, @text
      = link_to t('.destroy'), text_path(@text), :method => "delete", :confirm => t('.confirm'), :class => 'btn btn-danger btn-block' if can? :destroy, @text
      - modifications = ::Text.where(slug: @text.slug).includes(:modifications).map(&:modifications).flatten(1) - [@text.master]
      - if modifications.any?
        %h3= t(".modifications")
        %ul
          - modifications.each do |modification|
            %li
              = link_to_modification(modification)
              = "(#{link_to_user(modification.repository.user)})".html_safe
      
  .span9
    %h1= @text.title
    .text-text
      - if @text.master
        - @text.master.text.split(/\n/).each do |line|
          - case line
            - when /^Préambule/
              %h3.preamble= line
            - when /^Titre /
              %h2.title= line
            - when /^Article /
              %h3.article= line
            - when /^- /
              %p.list-item= line
            - else
              %p.paragraph= line